### ISSUE TITLE
Hot module replacement not working well, when reloading the full page, it takes lots of time, while instead sometimes when I just copy the url and paste it in new browser tab, renders immediately 

### ISSUE THREAD

**Issue by RosarioDiBartolo** [tylerlwsmith/vite-with-flask-backend#1]
I noticed how some times hot module replacement doesn’t work really well. When saving it my come to the whole page to be reloaded, and when it happens, it usually takes lot’s of time for the page to reload, while instead coping the url for the same page in another tab, loads the page almost immediately. I must say, I modified the home route, by using a “catch all route”, since I am using react router dom for routing , and modifying assets_url path of the flask app (it’s troublesome if you don’t do that, the catch all route won’t work for every path since it would aim for the assets)

By the way the hot module replacement problem persisted from before…

**Comment by tylerlwsmith** [comment]
It sounds like it could be one a few things:

1. There could be a package in your project that doesn't work well with HMR.
2. Your browser could have extensions that are slowing things down.
3. There could be something slow with the Vite or React HMR itself.

Unfortunately, these are outside the scope of this scaffolding example, and beyond my ability to provide meaningful support.

To rule out the scaffolding, you could try building a small version of your app with the same dependencies that only uses the default scaffold and isn't plugged into Flask. If the problem persists, you could try to figure out which project is causing the slowdown and open an issue in their repo.
